(in-package :gdenuf)

#+(and :x86-64 (or :win32 :windows))
(progn
  (cffi:defctype pointer_64_int :unsigned-long)
  (cffi:defctype int8 :int8)
  (cffi:defctype pint8 (:pointer :int8))
  (cffi:defctype int16 :short)
  (cffi:defctype pint16 (:pointer :short))
  (cffi:defctype int32 :int)
  (cffi:defctype pint32 (:pointer :int))
  (cffi:defctype int64 :long-long)
  (cffi:defctype pint64 (:pointer :long-long))
  (cffi:defctype uint8 :unsigned-char)
  (cffi:defctype puint8 (:pointer :unsigned-char))
  (cffi:defctype uint16 :unsigned-short)
  (cffi:defctype puint16 (:pointer :unsigned-short))
  (cffi:defctype uint32 :unsigned-int)
  (cffi:defctype puint32 (:pointer :unsigned-int))
  (cffi:defctype uint64 :unsigned-long-long)
  (cffi:defctype puint64 (:pointer :unsigned-long-long))
  (cffi:defctype long32 :int)
  (cffi:defctype plong32 (:pointer :int))
  (cffi:defctype ulong32 :unsigned-int)
  (cffi:defctype pulong32 (:pointer :unsigned-int))
  (cffi:defctype dword32 :unsigned-int)
  (cffi:defctype pdword32 (:pointer :unsigned-int))
  (cffi:defctype int_ptr :long-long)
  (cffi:defctype pint_ptr (:pointer :long-long))
  (cffi:defctype uint_ptr :unsigned-long-long)
  (cffi:defctype puint_ptr (:pointer :unsigned-long-long))
  (cffi:defctype long_ptr :long-long)
  (cffi:defctype plong_ptr (:pointer :long-long))
  (cffi:defctype ulong_ptr :unsigned-long-long)
  (cffi:defctype pulong_ptr (:pointer :unsigned-long-long))
  (cffi:defctype shandle_ptr :long-long)
  (cffi:defctype handle_ptr :unsigned-long-long)
  (cffi:defctype uhalf_ptr :unsigned-int)
  (cffi:defctype puhalf_ptr (:pointer :unsigned-int))
  (cffi:defctype half_ptr :int)
  (cffi:defctype phalf_ptr (:pointer :int))
  (cffi:defctype psize_t (:pointer ulong_ptr))
  (cffi:defctype ssize_t long_ptr)
  (cffi:defctype pssize_t (:pointer long_ptr))
  (cffi:defctype dword_ptr ulong_ptr)
  (cffi:defctype pdword_ptr (:pointer ulong_ptr))
  (cffi:defctype long64 :long-long)
  (cffi:defctype plong64 (:pointer :long-long))
  (cffi:defctype ulong64 :unsigned-long-long)
  (cffi:defctype pulong64 (:pointer :unsigned-long-long))
  (cffi:defctype dword64 :unsigned-long-long)
  (cffi:defctype pdword64 (:pointer :unsigned-long-long))
  (cffi:defctype kaffinity ulong_ptr)
  (cffi:defctype pkaffinity (:pointer kaffinity)))

#+(and :x86 (not :x86-64) (or :win32 :windows))
(progn
  (cffi:defctype pointer_64_int :unsigned-long)
  (cffi:defctype int8 :int8)
  (cffi:defctype pint8 (:pointer :int8))
  (cffi:defctype int16 :short)
  (cffi:defctype pint16 (:pointer :short))
  (cffi:defctype int32 :int)
  (cffi:defctype pint32 (:pointer :int))
  (cffi:defctype int64 :long-long)
  (cffi:defctype pint64 (:pointer :long-long))
  (cffi:defctype uint8 :unsigned-char)
  (cffi:defctype puint8 (:pointer :unsigned-char))
  (cffi:defctype uint16 :unsigned-short)
  (cffi:defctype puint16 (:pointer :unsigned-short))
  (cffi:defctype uint32 :unsigned-int)
  (cffi:defctype puint32 (:pointer :unsigned-int))
  (cffi:defctype uint64 :unsigned-long-long)
  (cffi:defctype puint64 (:pointer :unsigned-long-long))
  (cffi:defctype long32 :int)
  (cffi:defctype plong32 (:pointer :int))
  (cffi:defctype ulong32 :unsigned-int)
  (cffi:defctype pulong32 (:pointer :unsigned-int))
  (cffi:defctype dword32 :unsigned-int)
  (cffi:defctype pdword32 (:pointer :unsigned-int))
  (cffi:defctype int_ptr :int)
  (cffi:defctype pint_ptr (:pointer :int))
  (cffi:defctype uint_ptr :unsigned-int)
  (cffi:defctype puint_ptr (:pointer :unsigned-int))
  (cffi:defctype long_ptr :long)
  (cffi:defctype plong_ptr (:pointer :long))
  (cffi:defctype ulong_ptr :unsigned-long)
  (cffi:defctype pulong_ptr (:pointer :unsigned-long))
  (cffi:defctype uhalf_ptr :unsigned-short)
  (cffi:defctype puhalf_ptr (:pointer :unsigned-short))
  (cffi:defctype half_ptr :short)
  (cffi:defctype phalf_ptr (:pointer :short))
  (cffi:defctype shandle_ptr :long)
  (cffi:defctype handle_ptr :unsigned-long)
  (cffi:defctype psize_t (:pointer ulong_ptr))
  (cffi:defctype ssize_t long_ptr)
  (cffi:defctype pssize_t (:pointer long_ptr))
  (cffi:defctype dword_ptr ulong_ptr)
  (cffi:defctype pdword_ptr (:pointer ulong_ptr))
  (cffi:defctype long64 :long-long)
  (cffi:defctype plong64 (:pointer :long-long))
  (cffi:defctype ulong64 :unsigned-long-long)
  (cffi:defctype pulong64 (:pointer :unsigned-long-long))
  (cffi:defctype dword64 :unsigned-long-long)
  (cffi:defctype pdword64 (:pointer :unsigned-long-long))
  (cffi:defctype kaffinity ulong_ptr)
  (cffi:defctype pkaffinity (:pointer kaffinity)))
